# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-package-combination:
          - python-version: '3.8'
            packages: 'numpy==1.24.4'
          - python-version: '3.9'
            packages: 'numpy==1.24.4'
          - python-version: '3.9'
            packages: 'numpy==2.0.0'
          - python-version: '3.10'
            packages: 'numpy==1.24.4'
          - python-version: '3.10'
            packages: 'numpy==2.0.0'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-package-combination.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-package-combination.python-version }}
        cache: "pip"
        cache-dependency-path: pyproject.toml
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev-test]"
    - name: Checkout iqo modules
      run: |
        cd ..
        git clone https://github.com/prithviulm/qudi-iqo-modules.git
        cd qudi-iqo-modules
        pip install -e ".[dev-test]"
        cd ../qudi-core
    - name: Test different version of numpy
      run: pip install  ${{  matrix.python-package-combination.packages }}
    - name: Test with pytest
      run: |
        pytest --ignore=tests/fit_methods -s
    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
          name: code-coverage-report ${{ matrix.python-package-combination.python-version }} ,  ${{  matrix.python-package-combination.packages }}
          path: coverage
          retention-days: 5
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v4

 
